### ISSUE TITLE
Implement auto-reconnect logic (with ping & pong frames)

### ISSUE THREAD

**Issue by matbalez** [learn-co/learn-ide#178]

**Comment by drewprice** [comment]
Going to close this off for now. Rather than implementing for the terminal websocket, we simply added a listener on tree-view's websocket. When tree-view disconnects, the terminal socket resets its connection. When tree-view reconnects, the terminal also attempts to reset. This way, we are not forcing the connection status of terminal, but trying to make sure it is accurate.
