### ISSUE TITLE
Terminal text visually overlaps, not going to next line

### ISSUE THREAD

**Issue by saltillokid11** [learn-co/learn-ide#285]
reaching the end of the line with characters, terminal just stays on the same line and looks like it's overwritting the existing text but it's just visually overwritting
![newline](https://cloud.githubusercontent.com/assets/13110825/17904073/d8547b2a-693b-11e6-8942-47ce46926dfe.gif)

What it looks like
![pasted image at 2016_08_23 01_01 pm](https://cloud.githubusercontent.com/assets/13110825/17903743/91151fae-693a-11e6-9040-047c63ab134f.png)

**Comment by kjleitz** [comment]
This happens to me, too, and nothing I've tried has fixed it! Is this possibly because of the use of carriage return escape sequences (`\r`) in the terminal rather than newlines (`\n`)? I've been seeing them in `terminal.coffee` and it made me think there might be a connection.

I've encountered this kind of issue before (in plain ol' xterm) as the result of a poorly-formatted `$PS1`, but no amount of re-writing of the prompt string in `.bash_profile` (or any of the other usual fixes) relieves the problem here. That makes me think it might just be an issue with the implementation in `terminal.coffee`?

**Comment by drewprice** [comment]
Likely another "fix" to be gained with #200

**Comment by drewprice** [comment]
this happens by default with xterm. there _might_ be a way around it, but I would want to avoid any custom hack-ery. just need to dig through the docs and see if there is a nice way of accomplishing this.

Actually—it's probably not xterm that is doing this, but the fact that what is written to the terminal is explicitly what comes from the remote shell. So, there is no line break sent, because why would it be, and so the xterm cursor doesn't know what to do except start over? Maybe? Maybe not. Just need to dig around with it.

**Comment by drewprice** [comment]
see https://github.com/sourcelair/xterm.js/issues/179

Looks like the way to resolve is likely on the server side
