### ISSUE TITLE
'Create issue on the learn-ide-tree package' button points to wrong URL

### ISSUE THREAD

**Issue by The-Alchemist** [learn-co/learn-ide#385]
It points to https://github.com/learn-co/learn-ide-tree/issues/new, which gives a 404.  I get the impression it should be https://github.com/learn-co/learn-ide/issues/new

**Comment by joshrowley** [comment]
Ah, yeah thanks for catching this. I think this breaks because forked repos on Github do not have issue trackers. I'm not sure of the best way forward, I'd like to point the `learn-ide-tree` package to file issues on the main `learn-ide` repo, but I think that config value used for reporting issues ([here](https://github.com/learn-co/learn-ide-tree/blob/master/package.json#L7)) is also used for publishing on `apm` (and probably some other stuff). Not sure what the best way forward is yet, will need to investigate.

**Comment by joshrowley** [comment]
oh wait..we can turn on issues for the tree package, thanks @drewprice
