### ISSUE TITLE
Descriptive errors when the terminal is unable to connect

### ISSUE THREAD

**Issue by kjleitz** [learn-co/learn-ide#387]
I'm still a newbie, so I might be wrong here, but given the recent issues with the IDE disconnecting, could the terminal give a better error than a grayed-out "Unable to connect to Learn"? There's this error handler in `terminal.coffee` (learn-ide/lib/views/terminal.coffee):

```coffeescript
@terminal.on 'error', () =>
  @displayDisconnected()
```

Which calls this function:

```coffeescript
displayDisconnected: ->
  @terminalWrapper.off 'data'
  @terminalWrapper.element.style.color = '#666'
  @terminalWrapper.cursorHidden = true
  @terminalWrapper.write('Unable to connect to Learn\r')
```

But, as far as I know, an emitted `error` should pass the actual error along with it, right? So maybe that error handler could pass it to `displayDisconnected` and display it under the `'Unable to connect to Learn\r'` message, for more clarity. As of right now, there's no way to know _what_ error actually happened.

**Comment by drewprice** [comment]
@kjleitz you're right that the error event itself is passed along—the trouble is that that error usually doesn't have much information on it. However, where we control the server, we also control some of the errors that can be thrown by the websocket—to some extent.

So I think there is something here that we can potentially do to map codes, or else simply display them on a disconnect.

Thanks for poking around in this! It would certainly be helpful to provide some more logging on any kind of disconnect, be it an error or otherwise.
