### ISSUE TITLE
ctrl-p is difficult with such a huge project directory

### ISSUE THREAD

**Issue by notnotdrew** [learn-co/learn-ide#396]
I wonder if we can configure it to start looking closer to the active path than the project

cc @aturkewi

**Comment by aturkewi** [comment]
I think this could be super helpful as that's how I navigate my file tree a lot of the time. I'd say low priority though.
Thanks for creating this :)

**Comment by drewprice** [comment]
One idea: the tree-view could reflect only your current terminal directory. We'd just need to wrap `cd` so that it writes the new path to the [`custom_commands.log`](https://github.com/learn-co/nsync-fs#custom-commands), which can then be handled by [`learn-ide-tree`](https://github.com/learn-co/learn-ide-tree/blob/f3314a482cc19b42bcc99f9fc40c6b38a9ef0dbc/lib/nsync/custom-commands.coffee) to swap out the client's current project (eg: [updateProject](https://github.com/learn-co/learn-ide-tree/blob/f3314a482cc19b42bcc99f9fc40c6b38a9ef0dbc/lib/nsync/atom-helper.coffee#L54-L61)).

**Comment by aturkewi** [comment]
I think that would be really cool! The other big win for that feature idea Drew is that I think it would really start highlighting to students where they are in the terminal. I see a lot of people get confused on reconnect because they're no longer in a lab, but all the files for their lab are still showing up top. 

The only downside I could for see here is that it might make it difficult for students to be in one lab and be able to easily look back at another one. Github?
