### ISSUE TITLE
the `atom` and `apm` executable binaries are hijacked by the Learn IDE

### ISSUE THREAD

**Issue by notnotdrew** [learn-co/learn-ide#414]
notes from @aturkewi:
>since i update the Learn IDE, it's hijacked my `atom` command in my local terminal... just uninstalled the IDE, `rm /usr/local/bin/atom` (to remove the symlink), recreated the correct one with `ln -s /Applications/Atom.app/Contents/Resources/app/atom.sh /usr/local/bin/atom`, re-installed the Learn IDE, and it hijacked the symlink again.

*Might* be related to https://github.com/learn-co/learn-ide/commit/07719f3707584b925b23de5d32de15b080905975, maybe?

**Comment by drewprice** [comment]
Not incredibly blocking, as most of our users do not also use Atom, and not from the command line (where this problem occurs)

**Comment by aturkewi** [comment]
From `#learn-experts` this morning:
![screen shot 2017-02-27 at 11 46 12 am](https://cloud.githubusercontent.com/assets/13033515/23370350/5d2fa3e4-fce2-11e6-965f-55a07bd30f5b.png)

**Comment by aturkewi** [comment]
^ That was just meant as a confirmation that others have seen this as well.

**Comment by stanclarke-jr** [comment]
I have also run into this issue. Removing Atom from my system also remove Learn IDE.

**Comment by drewprice** [comment]
The command seems to oscillate between the two programs. That is, if I open the Learn IDE, `atom` will run the Learn IDE. If I then open Atom, `atom` will run Atom. Which does seem related to the code that https://github.com/learn-co/learn-ide/commit/07719f3707584b925b23de5d32de15b080905975 affects, but that specific change shouldn't be behind this (as that change changes code that runs on Windows only).

@stanclarke-jr That sounds like it might be a different issue. Can you provide a bit more context into what happened? Your OS, IDE version, how you removed Atom & how you discovered the IDE was also removed—anything that might help us figure out what might have happened.

**Comment by stanclarke-jr** [comment]
@drewprice My experience was that the command `atom`, without the Learn IDE or Atom instances running, opened Learn IDE. 

I initially came across this issue because nothing happened when I clicked OPEN to fork the lab. I decided to remove Atom using `sudo apt purge atom` to see if this would resolve the issue, but discovered that Learn IDE had also been removed. I have since re-installed Learn IDE, but not Atom. Clicking OPEN still doesn't work, but `learn open` does.

I initially installed Atom by downloading the .deb from [atom.io](https://atom.io).

OS: Ubuntu 16.10, kernel 4.4.0-45-generic
IDE: v4.2.0

**Comment by aturkewi** [comment]
Hey @stanclarke-jr thanks for adding some notes to this.

As far as I know, the Open button simply does not work on Linux. Here is a great article with the manual steps: http://help.learn.co/the-learn-ide/common-ide-questions/learn-open-button-issues

As far as the `atom` command goes. It seems that it becomes attached to whichever program opened last. So if I open up Atom (not using the terminal), it'll take over the `atom` command, but if I then open up the Learn IDE (again, not using the terminal), it then takes over the `atom` command. Easiest way to switch it to what you want is to fully quit both, and then manually open the one that you want `atom` to be used for. I think it should really be Atom, because as far as I know, there is never a good reason to open up the Learn IDE from the terminal like that.

**Comment by michaelbukachi** [comment]
I'd like to report this issue also. The moment I installed Learn IDE, I couldn't access all my previous projects. In fact when installing Learn IDE, one of the lines printed in the terminal are:
`Unpacking atom (2.5.1) over (1.15.0) ...` 
Reinstalling the atom package replaces the Learn IDE one and my previous project configurations are restored. Does this mean I cannot install both at the same time??

**Comment by drewprice** [comment]
@michaelbukachi how are you installing the Learn IDE? Can you also provide some details on your operating system?

I'm a little unclear on what you mean by not being able to access your "previous projects" and the restoration of your "previous project configurations"—can you explain that a bit more?

There are some known issues running Atom and the Learn IDE on the same system, but nothing yet  that should prevent either them from working. That being said, if you are already an Atom user, I would typically recommend just installing the `learn-ide` package, which we have instructions for [here](http://help.learn.co/the-learn-ide/the-basics-of-the-learn-ide/manually-install-the-learn-ide-from-atom).

**Comment by michaelbukachi** [comment]
@drewprice I mean when I try to open a project from before (before I installed learn ide), the navigation tree is just blank. I'll try the package option though and see if it will work.

**Comment by ivanpilot** [comment]
Same here. The latest version of learn IDE totally hijacks my atom. can't use normal atom command like open (file, folder, project), save, save as, etc. It also messed up with the views by adding a third panel (second navigation tree) that was relating to my project from learn, and not my local projects and couldn't get rid of that panel. I uninstalled learn IDE and every related package in atom.

**Comment by drewprice** [comment]
@ivanpilot The "hijacking" you're describing is actually the intended effect of the Learn IDE. The reason for this is that the Learn IDE is actually a remote development environment, using Atom as a client. Therefore, all of the file actions are intercepted and routed to the remote environment where are they performed, and then those changes are synced back to the client. The second tree is a reflection of the remote filesystem (and it should have displayed a notification explaining why there were two?).

@michaelbukachi Similarly, the Learn IDE tree is setting your remote filesystem as the project.

There is currently a clear distinction between "vanilla" Atom and the Learn IDE: if you are using the Learn IDE application, or using Atom with the Learn IDE package enabled, you **will not** be able to use Atom outside of the context of being a client for a remote development system. You will have to disable the Learn IDE packages in order to use Atom outside of that context.

**Comment by aturkewi** [comment]
To give an update on the 'hijacking':

When you install and open the Learn IDE, it re-writes the `atom` shortcut. Any time you see this happen, you can fix it by running:
```
rm /usr/local/bin/atom
ln -s /Applications/Atom.app/Contents/Resources/app/atom.sh /usr/local/bin/atom
```
(I've saved this as a function in my bash_profile for quick access).

As of a recent update, I've found this only partially fixes the issue. To get back to 'vanilla' atom, you then have to go to preferences and open up your installed packages and disable all three packages that start with `learn`. This should put Atom back in place as it was before. 

Note: You will have to re-enable all these packages when you want to use the Learn IDE.

**Comment by drewprice** [comment]
@aturkewi only adding to your bandaid, but you could also disable the learn-ide packages within your function that's correcting the symlink.

```bash
apm disable learn-ide
apm disable learn-ide-tree
apm disable learn-ide-notifications
```

One potential catch is that if you've lost the `atom` binary, you've probably also lost the `apm` binary—but I'm sure it can be restored similarly.

**Comment by aturkewi** [comment]
Just to come full circle on this. My workaround is adding these two functions to my `~/.bash_profile`:

```
function atom-sym {
  rm /usr/local/bin/atom
  ln -s /Applications/Atom.app/Contents/Resources/app/atom.sh /usr/local/bin/atom
  apm disable learn-ide
  apm disable learn-ide-tree
  apm disable learn-ide-notifications
}

function atom-ide {
  rm /usr/local/bin/atom
  ln -s /Applications/Atom.app/Contents/Resources/app/atom.sh /usr/local/bin/atom
  apm enable learn-ide
  apm enable learn-ide-tree
  apm enable learn-ide-notifications
}
```

Running `atom-sym` will set the `atom` command to act as it normally would and running `atom-ide` re-enables the IDE functionality when needed.

**Comment by veekas** [comment]
I use Atom separately from Learn IDE as well and started having this problem when I updated Learn the other day. Thanks for the workaround functions, @aturkewi!
