### ISSUE TITLE
IDE version checking broken

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#431]
Selecting Help -> Check for Update always returns product is up-to-date even though it is not. On 3-Apr-17 21:49 ET, my version was 2.4.0 and the check update said up to date. I downloaded and installed the IDE and the version went to 2.4.2.

**Comment by drewprice** [comment]
Hey @jcpny1—this is actually by design. When you check for updates, you are hitting an endpoint on learn.co which we control and only advance when we want all IDE users to move to the latest version. The patches `2.4.1` and `2.4.2` were relatively insignificant, and therefore our product team decided it did not warrant pushing update notifications for all existing users.

In `2.5.0` (which has just entered beta), you will have the option to subscribe to "bleeding versions" which will keep you up-to-date with the very latest, including beta releases.
