### ISSUE TITLE
Saving file not clearing modified status

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#432]
Windows 10/IDE 2.4.2
When I go to close a file that has had changes saved (with Ctrl-S), a popup asks me to save or not to save. There are no unsaved changes that I'm aware of that should cause that popup to appear.

**Comment by drewprice** [comment]
This issue should be resolved in 2.5.0

In some cases, the issue here was that `ctrl-s` was not registered as a shortcut when the terminal is in focus, as `ctrl-s` is actually a control character in the terminal; however, it's a pretty obscure control character so we've replaced it with the keymap to save the editor.

More often though, I think this has been an issue with line endings. See https://github.com/learn-co/learn-ide-tree/pull/42#issue-216838576
