### ISSUE TITLE
Lost edits

### ISSUE THREAD

**Issue by jcpny1** [learn-co/learn-ide#439]
Windows 10/IDE 2.4.2
IDE crapped out. When restarted, local edits lost.

**Comment by drewprice** [comment]
Hey @jcpny1—thanks for reporting.

We'd need to know more what you mean by "local edits" in order to diagnose this further.

The IDE, generally, will not persist "local edits". It is designed to treat the remote server you are connected as the source of truth. So unless changes are saved (which happens on the server first) when you attempt to save a file, they will usually be lost.

The exception to this is that Atom itself does some work to recover buffers that have not been written to the local disk. I'm not sure of the details with that though, so I can't so for sure if/how/when it would catch something like this.

Also, if a local file that is managed by the IDE is edited from outside of the IDE, those edits will be overwritten when the IDE is launched. Again, the server is taken to be the source of truth.

**Comment by jcpny1** [comment]
By local edits, I meant local edits that I made using the IDE while on my computer. I suppose 'local' was unnecessary. I suspect the problem is unreliable server service as I've had quite a few problems in the past. Most recently, when I Ctrl-S save a file, a blue circle still appears on the file tab as if the file had not been saved. When I go to close the tab, it asks me if I want to save changes, even though the changes had already been saved (as noted when re-executing the file to see the expected new behavior). Other current problems are: expanding the width of the tree view causes the console to not be formatted properly, and when the IDE is first opened, the console width seems to be set at about 35 characters and cannot be changed without doing an IDE reconnect.

**Comment by jcpny1** [comment]
Also, the Help->Report Issue link takes you to the Atom github page, which would not be the correct place to report an issue.
