### ISSUE TITLE
command line visible then hidden after running test

### ISSUE THREAD

**Issue by kvignali** [learn-co/learn-ide#466]
https://www.screencast.com/t/JVDyLHDMc

**Comment by drewprice** [comment]
It actually looks like something is potentially going on with either that lab, that test, or the gem—the test is returning, which brings the prompt back, but then something is being written to stdout after the fact—usually something like this would be caused by a background process of some sort. 

Not positive, but I think `learn-test-sender` (which is what's throwing the second error that makes it look all broken) might be related to the experiment we've been running with the `learn-test` gem.

We should look into this, but it seems very unlikely that this is related to this IDE release.

**Comment by drewprice** [comment]
Issue moved to [learn-co/learn-test #41](https://github.com/learn-co/learn-test/issues/41) via [**ZenHub**](https://www.zenhub.com/)
