### ISSUE TITLE
emulator state is not shared across new instances (i.e. new windows have bank emulators)

### ISSUE THREAD

**Issue by kvignali** [learn-co/learn-ide#471]

**Comment by drewprice** [comment]
This is likely because the terminal socket connection actually stays open, so that when the new window is opened, no new data is sent to the terminal, so it just looks empty. The same thing happens when you simply open a new window.

One fix for this would be to continually write terminal output to a `localStorage` cache that new windows could read from if they connect to an existing socket (i.e. on atom-socket's `open:cached` event in [`lib/terminal.js`](https://github.com/learn-co/learn-ide/blob/6cf86624065832d6a0461a928b616b6fdabebe65/lib/terminal.js#L29-L32)).

**Comment by drewprice** [comment]
Also... there's gotta be a way to get the contents of an existing emulator and send them over to a new instance. So that might be another option.

**Comment by joshrowley** [comment]
@drewprice That should be happening already, unless the underlying code changed.

**Comment by joshrowley** [comment]
@drewprice 

yeah, back in `2.4`, this is what was doing it (prob not a good place for it): https://github.com/learn-co/learn-ide/blob/v2.4.2/lib/views/terminal-wrapper.coffee#L10-L18

we still have the cleanup action happening in 2.5: https://github.com/learn-co/learn-ide/blob/33fdbc13c5d2aa2dae78a4d84531819361310b8c/lib/learn-ide.js#L193

**Comment by joshrowley** [comment]
`restore` was then called when new terminal views were instantiated: https://github.com/learn-co/learn-ide/blob/v2.4.2/lib/views/terminal.coffee#L30

**Comment by drewprice** [comment]
Oh dope, thanks @joshrowley. I thought I remembered something about this being a thing we did.
